### PR TITLE
feat: added more wallet support

### PR DESCRIPTION
**Pull request by devon-n**
- Removed only wallet connect and metamask as supported wallets allowing more to connect

### CODE REVIEW

**Comment by rohan-tez** [comment]
The only thing here is when I try to connect with my trust wallet mobile app it doesn't work. I end up on the following page:
Screenshot 2024-08-15 at 14 56 02

When I click "Switch Network" button, I receive an error on my Trust Wallet app saying "An Unknown Error Occurred."

**Comment by devon-n** [comment]
I

> The only thing here is when I try to connect with my trust wallet mobile app it doesn't work. I end up on the following page: Screenshot 2024-08-15 at 14 56 02
> 
> When I click "Switch Network" button, I receive an error on my Trust Wallet app saying "An Unknown Error Occurred."

I got it to work by adding it as a custom network first then it allows us to connect.

**Comment by rohan-tez** [comment]
> I
> 
> > The only thing here is when I try to connect with my trust wallet mobile app it doesn't work. I end up on the following page: Screenshot 2024-08-15 at 14 56 02
> > When I click "Switch Network" button, I receive an error on my Trust Wallet app saying "An Unknown Error Occurred."
> 
> I got it to work by adding it as a custom network first then it allows us to connect.

Cool makes sense LGTM then 👍

**Review by rohan-tez — APPROVED** [review]
LGTM!

**Review by Camillebzd — APPROVED** [review]

**Pull request merged**
